name: dartling_todo_mvc
version: 0.0.0
description: "Todo.Mvc done with dartling. \r\nBased on TodoMVC in Dart. \r\ndartling\
  \ is a domain model framework."
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
documentation: http://goo.gl/VGH8KP
dependencies:
  browser: any
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'
  dartling_default_app:
    git: 'https://github.com/dzenanr/dartling_default_app.git'
